add deps.edn usage section
weavejester/codox pull request #201
Opened 2021-04-29 16:47 UTC by wactbprot

2021-04-29 18:40 UTC, weavejester requested changes
Can you also change the commit message to:

    Add deps.edn usage section to README

(Please don't open a new PR for these changes - just update the existing commit.)

2021-04-29 18:40 UTC, weavejester commented on README.md
> +### deps.edn format
This should be `### deps.edn`

2021-04-29 18:40 UTC, weavejester commented on README.md
> +If `:dev` is the alias you work on run:
Why assume you're running via an alias?

2021-04-29 19:59 UTC, seancorfield commented on README.md
> +If `:dev` is the alias you work on run:
If you're working with a system (such as Polylith) where the source code isn't on your path by default -- only when you add `:dev` to the mix. I'm assuming Codox needs to load the source files and therefore they need to be compilable which means they need to have the correct classpath.

We would have the same issue in our monorepo at work (if my assumption is correct) and we could need `clojure -X:everything:codox` to make it work.

2021-04-29 20:00 UTC, seancorfield commented on README.md
> +clj -A:dev -X:codox
Since it is a non-interactive use, it's better practice to recommend `clojure` instead of `clj` (to avoid the unnecessary `rlwrap` invocation).

2021-04-29 20:28 UTC, seancorfield commented on README.md
> +clojure -A:dev -X:codox
`clojure -X:dev:codox` would be easier -- but let's wait and see what @weavejester says in response.

2021-04-29 23:11 UTC, weavejester commented on README.md
> +If `:dev` is the alias you work on run:
If the example command was just `clojure -X:codox`, presumably we could leave it up to the reader to add in the `dev` alias, or whatever they happen to want to use.

2021-04-29 23:24 UTC, seancorfield commented on README.md
> +If `:dev` is the alias you work on run:
Given that folks have already tripped over the fact that `clojure -X:codox` is not enough for projects where an additional alias is needed to get source on the classpath, I think it should at least have a note about that.

Perhaps:

Run Codox via `-X` like this:

```shell
clojure -X:codox
```

> Note: Codox expects the code it analyzes to be on the classpath so you may need to specify additional aliases from your project to make that happen, e.g., `clojure -X:dev:codox`.

2021-05-01 16:23 UTC, wactbprot commented
I think @seancorfield  [version](https://github.com/weavejester/codox/pull/201#discussion_r623482236) is a very nice suggestion.

2021-05-01 16:51 UTC, seancorfield commented
This latest change is missing a basic example of how to run Codox:

Run Codox via `-X` like this:

```bash
clojure -X:codox
```

2021-05-01 17:05 UTC, weavejester commented on README.md
> +If `:dev` is the alias you work on run:
That's fine, I think.

2021-05-01 17:09 UTC, weavejester requested changes

2021-05-01 17:09 UTC, weavejester commented on README.md
> +> Note: Codox expects the code it analyzes to be on the classpath so you
This probably shouldn't be a blockquote, since you're not quoting anything.

2021-05-01 17:09 UTC, weavejester commented on README.md
> +You can specify the `:source-paths` and the following options as a
Unless we want to do this for every option, we should remove this.

2021-05-01 22:52 UTC, seancorfield commented
This looks good to me now. Thanks, both of you.

2021-05-03 11:46 UTC, wactbprot commented
What do you think @weavejester? Any further comments?

2021-05-03 14:16 UTC, weavejester approved these changes

2021-05-03 14:16 UTC, merged

2021-05-03 14:16 UTC, weavejester commented
Looks good.